name: onedrive_mass_upload
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Kai Page <kaibug@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  args: ^1.5.2
  json_annotation: ^3.0.0
  logger: ^0.7.0
  meta: ^1.1.7
  oauth2: ^1.3.0
  path: ^1.6.4
  shelf: ^0.7.5

dev_dependencies:
  build_runner: ^1.6.5
  json_serializable: ^3.2.0
  test: ^1.5.0

  quantaly_lints:
    git:
      url: https://github.com/Quantaly/dart_lints
